listener 1883
protocol mqtt

listener 8080
protocol websockets

allow_anonymous true

persistence true
persistence_location C:/xampp/htdocs/food-order-system/mosquitto-data/
persistence_file mosquitto.db

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
